### PR TITLE
Add collection naming & ObjectId documentation

### PR DESCRIPTION
**Pull request by joshuadavidson**
Document collection naming scheme and ability to rename collection with `CollectionName` attribute.
Document optional use of `MongoDB.Bson.ObjectId` for entity keys.
Update headers for clarity.

### CODE REVIEW

**Comment by joshuadavidson** [comment]
Thanks for a great package!

**Comment by alexandre-spieser** [comment]
You're welcome, thanks for your contribution 👍

**Comment by xclud** [comment]
@alexandre-spieser please update the nuget package as well. I am waiting to update my project deps.

@joshuadavidson Thanks. Useful amount of code.

**Comment by alexandre-spieser** [comment]
@xclud there is nothing to update, those features are already supported in the current version, they are brought by my other project `MongoDbGenericRepository` https://github.com/alexandre-spieser/mongodb-generic-repository. Enjoy 💃

**Pull request merged**
